export default {
  "common": {
    "back": "Back",
    "next": "Next",
    "cancel": "Cancel",
    "confirm": "Confirm",
    "search": "Search",
    "loading": "Loading...",
    "error": "An error occurred",
    "retry": "Retry",
    "save": "Save",
    "edit": "Edit",
    "delete": "Delete",
    "success": "Success",
    "or": "or",
    "skip": "Skip"
  },

  "auth": {
    "login": "Login",
    "signup": "Sign Up",
    "logout": "Logout",
    "email": "Email Address",
    "password": "Password",
    "welcome": "Login",
    "loginSubtitle": "Welcome to Templestay",
    "emailPlaceholder": "Enter your email",
    "passwordPlaceholder": "Enter your password",
    "orLoginWith": "Or login with",
    "noAccount": "Don't have an account?",
    "signUp": "Sign Up",
    "forgotPassword": "Forgot Password?",
    "loginWithGoogle": "Login with Google",
    "loginWithKakao": "Login with Kakao",
    "loginWithNaver": "Login with Naver",
    "invalidEmail": "Please enter a valid email address",
    "enterPassword": "Please enter your password",
    "loginFailed": "Login Failed",
    "loginError": "An error occurred during login",
    "loggingIn": "Logging in...",
    "fillAllFields": "Please fill in all fields",
    "passwordMinLength": "Password must be at least 6 characters",
    "agreeToTerms": "Please agree to terms and conditions",
    "signUpComplete": "Sign up completed successfully",
    "googleLogin": "Google Login",
    "googleLoginInstructions": "Please complete the login process in your browser",
    "googleLoginError": "Google login failed",
    "welcomeToApp": "Welcome to Templestay",
    "findPeaceOfMind": "Find your inner peace",
    "emailLogin": "Email Login",
    "continueWithGoogle": "Continue with Google",
    "name": "Name",
    "phoneNumber": "Phone Number",
    "signUpFailed": "Sign Up Failed",
    "signUpError": "An error occurred during sign up",
    "agreeToTermsText": "I agree to terms and conditions",
    "signingUp": "Signing Up...",
    "signUpButton": "Sign Up",
    "backToLogin": "Back to Login",
    "googleLoggingIn": "Logging in with Google..."
  },
  "analysis": {
    "matchingWithTemples": "Matching with temples...",
    "generatingRecommendations": "Generating recommendations...",
    "preparingPersonalized": "Preparing personalized results...",
    "aiCustomAnalysis": "AI custom analysis in progress...",
    "findingPerfectTemplestay": "Finding your perfect templestay...",
    "didYouKnow": "Did you know?",
    "templestayHistory": "Templestay has a 1,700-year history in Korea",
    "collectingPreferences": "Collecting your preferences...",
    "analyzingInputData": "Analyzing input data...",
    "matchingTemples": "Matching temples...",
    "result": {
      "analysisComplete": "Analysis Complete",
      "profileCompleted": "Your profile has been completed!",
      "yourCharacteristics": "Your Characteristics",
      "peaceSeekerType": "Peace Seeker Type",
      "peaceSeekerDescription": "You seek quiet moments and deep inner reflection. You prefer meditation and peaceful environments.",
      "recommendedTemples": "Recommended Temples",
      "startJourney": "Start Your Journey",
      "autoRedirect": "Automatically redirecting to main page...",
      "characteristics": {
        "meditation": "Meditation enthusiast",
        "quietTime": "Enjoys quiet time",
        "deepConversation": "💭 Values deep conversation"
      },
      "temples": {
        "bulguksa": {
          "name": "Bulguksa Temple",
          "location": "Gyeongju, Gyeongbuk",
          "reason": "Perfect for meditation and quiet reflection"
        },
        "haeinsa": {
          "name": "Haeinsa Temple",
          "location": "Hapcheon, Gyeongnam",
          "reason": "Home to ancient Buddhist scriptures, ideal for deep contemplation"
        },
        "songgwangsa": {
          "name": "Songgwangsa Temple",
          "location": "Suncheon, Jeonnam",
          "reason": "Known for its peaceful atmosphere and meditation programs"
        }
      }
    }
  },
  "language": {
    "selectLanguage": "Select Language",
    "selectLanguageDescription": "Choose your preferred language\nfor the Templestay app",
    "english": "English",
    "korean": "한국어",
    "japanese": "日本語",
    "chinese": "中文"
  },
  "home": {
    "title": "Templestay",
    "welcome": "Find your inner peace",
    "viewTemples": "View All Temples",
    "recommendedTemples": "Recommended Temples",
    "nearbyTemples": "Nearby Temples",
    "popularTemples": "Popular Temples",
    "gyeongbukRecommended": "Gyeongbuk Temple Recommendations",
    "myLocation": "My Location",
    "locationBasedRecommendation": "Location-based recommendations",
    "recommendedTemplesSection": "Gyeongbuk Recommended Temples",
    "seeAll": "See All",
    "regions": {
      "all": "All",
      "gyeongju": "Gyeongju",
      "andong": "Andong",
      "yeongju": "Yeongju",
      "pohang": "Pohang",
      "gumi": "Gumi"
    }
  },
  "temples": {
    "listTitle": "Temple List",
    "detailsTitle": "Temple Information",
    "templestayPrograms": "Templestay Programs",
    "reserveNow": "Reserve Now",
    "price": "Price",
    "duration": "Duration",
    "capacity": "Capacity",
    "nearbyAttractions": "Nearby Attractions"
  },
  "reservation": {
    "selectDate": "Select Date",
    "selectTime": "Select Time",
    "selectPeople": "Select People",
    "guestInfo": "Guest Information",
    "payment": "Payment",
    "confirmation": "Reservation Confirmation",
    "myReservations": "My Reservations",
    "reservationComplete": "Reservation Complete",
    "reserve": "Reserve",
    "reserveNow": "Reserve Now",
    "booking": "Booking",
    "bookingDetails": "Booking Details",
    "checkIn": "Check-in",
    "checkOut": "Check-out",
    "guests": "Guests",
    "adult": "Adult",
    "child": "Child",
    "totalPrice": "Total Price",
    "pricePerNight": "Price per night",
    "serviceFee": "Service Fee",
    "taxes": "Taxes",
    "phoneNumber": "Phone Number",
    "email": "Email",
    "specialRequests": "Special Requests",
    "paymentMethod": "Payment Method",
    "creditCard": "Credit Card",
    "bankTransfer": "Bank Transfer",
    "confirmReservation": "Confirm Reservation",
    "reservationSuccess": "Reservation Successful",
    "reservationFailed": "Reservation Failed",
    "bookingReference": "Booking Reference",
    "viewDetails": "View Details",
    "cancel": "Cancel",
    "modify": "Modify",
    "status": {
      "confirmed": "Confirmed",
      "pending": "Pending",
      "cancelled": "Cancelled",
      "completed": "Completed"
    }
  },
  "map": {
    "search": "Search places, addresses",
    "myLocation": "My Location",
    "nearbyAttractions": "Nearby Attractions Recommendations",
    "templeLocation": "Temple Location",
    "locationPermissionDenied": "Location permission denied",
    "noSearchResults": "No search results found. Try searching for Gyeongju, Andong, Yeongju, etc.",
    "attractionSubtitle": "Beautiful attractions around temples",
    "searchLocation": "Search Location"
  },
  "market": {
    "title": "Temple Market",
    "categories": {
      "all": "All",
      "experience": "Experience",
      "goods": "Goods",
      "food": "Food",
      "books": "Books"
    },
    "products": {
      "templestayExperience": "Templestay 1 Night 2 Days Experience",
      "templestayDescription": "Peaceful 1 night 2 days experience at Bulguksa",
      "incenseSet": "Natural Sandalwood Gift Set",
      "incenseDescription": "Premium incense to purify the mind",
      "cookingClass": "Temple Food Cooking Class",
      "cookingDescription": "Learn traditional Korean temple cuisine",
      "meditationCushion": "Meditation Cushion",
      "meditationDescription": "Comfortable cushion for meditation practice",
      "teaSet": "Traditional Tea Set",
      "teaDescription": "Enjoy peaceful tea time",
      "buddhismBook": "Introduction to Buddhism",
      "bookDescription": "Essential guide for understanding Buddhism"
    },
    "badges": {
      "popular": "Popular",
      "new": "New",
      "sale": "Sale",
      "bestseller": "Bestseller"
    },
    "price": "Price",
    "originalPrice": "Original Price",
    "rating": "Rating",
    "reviews": "Reviews",
    "addToCart": "Add to Cart",
    "buyNow": "Buy Now",
    "viewProduct": "View Product",
    "outOfStock": "Out of Stock",
    "inStock": "In Stock",
    "free": "Free",
    "discount": "Discount"
  },
  "profile": {
    "myProfile": "My Profile",
    "editProfile": "Edit Profile",
    "settings": "Settings",
    "language": "Language",
    "notifications": "Notifications",
    "privacy": "Privacy",
    "favorites": "Favorites",
    "notices": "Notices",
    "support": "Support Center",
    "recentReservation": "Recent Reservation",
    "visitedPlaces": "Visited Places",
    "logout": "Logout",
    "welcome": "Hello!",
    "user": "User",
    "welcomeSubtitle": "Let's find inner peace together",
    "taxiService": "🚗 Templestay Taxi Service",
    "taxiDescription": "Convenient transportation for comfortable travel",
    "seeMore": "See More",
    "logoutConfirm": "Are you sure you want to logout?",
    "logoutError": "An error occurred during logout",
    "testSuccess": "Test Success",
    "testFailed": "Test Failed",
    "testError": "Test Error",
    "testErrorMessage": "An error occurred during testing",
    "developerTools": "Developer Tools",
    "databaseTest": "🔍 Database Test",
    "databaseTesting": "Database Testing...",
    "colorSystemTest": "Color System Test",
    "reservationTest": "📝 Reservation Test",
    "reservationHistory": "Reservation History",
    "visitedTemples": "Visited Temples"
  },
  "templePreference": {
    "title": "Please select your preferred experiences",
    "subtitle": "Select activities you're interested in\nand we'll recommend personalized templestays",
    "selectedCount": "selected",
    "hint": "(Selecting 3 or more will give more accurate recommendations)",
    "customAnalysis": "Custom Analysis",
    "nextStep": "Next",
    "activities": {
      "meditation": "Meditation and Zen",
      "meditationDesc": "Time to find peace of mind",
      "templeFoodExperience": "Temple Food Experience", 
      "templeFoodDesc": "Learn healthy temple cuisine",
      "bowingPractice": "108 Bow Practice",
      "bowingDesc": "Traditional repentance practice",
      "teaTime": "Tea Time with Monk",
      "teaTimeDesc": "Conversation and tea with monks",
      "dawnService": "Dawn Service",
      "dawnServiceDesc": "Early morning prayer and meditation",
      "forestWalk": "Forest Path Walking",
      "forestWalkDesc": "Walking meditation in nature",
      "scriptCopying": "Sutra Copying",
      "scriptCopyingDesc": "Concentration and mental cultivation",
      "lotusLanternMaking": "Lotus Lantern Making",
      "lotusLanternDesc": "Traditional craft experience",
      "communalWork": "Communal Work",
      "communalWorkDesc": "Joy of working together",
      "stoneTowerBuilding": "Stone Tower Building", 
      "stoneTowerDesc": "Building stone towers with wishes",
      "bellTolling": "Temple Bell Tolling",
      "bellTollingDesc": "Sacred bell sound experience",
      "sunriseViewing": "Sunrise Viewing",
      "sunriseDesc": "Dawn at the mountain temple"
    }
  },
  "locationPreset": {
    "title": "Please select your location",
    "subtitle": "We'll recommend templestays\nthat suit you",
    "currentLocation": "Use Current Location",
    "currentLocationDesc": "We'll automatically find temples near you",
    "currentLocationAlert": {
      "title": "Use Current Location",
      "message": "We'll use location services to recommend nearby temples.",
      "allow": "Allow",
      "cancel": "Cancel"
    },
    "orDivider": "or",
    "directSearch": "Direct Search",
    "searchPlaceholder": "Search city name (e.g., Gyeongju)",
    "popularLocations": "Popular Templestay Regions",
    "locationAlert": {
      "title": "Location Selection",
      "message": "Please select a location or search."
    },
    "popularCities": {
      "gyeongju": "Gyeongju",
      "gyeongjuDesc": "Historic city with Bulguksa and Seokguram",
      "andong": "Andong", 
      "andongDesc": "Home of Hahoe Village and traditional culture",
      "yeongju": "Yeongju",
      "yeongjuDesc": "Beautiful scenery of Sobaeksan and Buseoksa",
      "pohang": "Pohang",
      "pohangDesc": "Templestay with the sea"
    }
  },
  "navigation": {
    "home": "Home",
    "temples": "Temples",
    "map": "Map",
    "transportation": "Transportation",
    "market": "Market",
    "myPage": "My Page"
  },
  "onboarding": {
    "welcomeTitle": "Welcome to TempleBuk",
    "welcomeSubtitle": "Begin your joyful templestay experience!",
    "profileImage": "Profile Image",
    "openGallery": "Open Gallery",
    "setDefaultImage": "Set Default Image",
    "enterName": "Enter your name",
    "start": "Start",
    "permissionNeeded": "Permission needed",
    "photoLibraryPermission": "Please grant permission to access your photo library",
    "invalidImage": "Invalid image selected",
    "failedToPickImage": "Failed to pick image. Please try again."
  }
};