export default {
  "common": {
    "back": "戻る",
    "next": "次へ",
    "cancel": "キャンセル",
    "confirm": "確認",
    "search": "検索",
    "loading": "読み込み中...",
    "error": "エラーが発生しました",
    "retry": "再試行",
    "save": "保存",
    "edit": "編集",
    "delete": "削除",
    "success": "成功",
    "or": "または",
    "skip": "スキップ"
  },

  "auth": {
    "login": "ログイン",
    "signup": "サインアップ",
    "logout": "ログアウト",
    "email": "メールアドレス",
    "password": "パスワード",
    "forgotPassword": "パスワードを忘れましたか？",
    "loginWithGoogle": "Googleでログイン",
    "loginWithKakao": "Kakaoでログイン",
    "loginWithNaver": "Naverでログイン",
    "invalidEmail": "有効なメールアドレスを入力してください",
    "enterPassword": "パスワードを入力してください",
    "loginFailed": "ログイン失敗",
    "loginError": "ログイン中にエラーが発生しました",
    "loggingIn": "ログイン中...",
    "noAccount": "アカウントをお持ちでないですか？サインアップ",
    "fillAllFields": "すべてのフィールドを入力してください",
    "passwordMinLength": "パスワードは最低6文字以上である必要があります",
    "agreeToTerms": "利用規約に同意してください",
    "signUpComplete": "サインアップが正常に完了しました",
    "googleLogin": "Googleログイン",
    "googleLoginInstructions": "ブラウザでログインプロセスを完了してください",
    "googleLoginError": "Googleログインに失敗しました",
    "welcomeToApp": "テンプルステイへようこそ",
    "findPeaceOfMind": "心の平和を見つけましょう",
    "emailLogin": "メールログイン",
    "continueWithGoogle": "Googleで続行"
  },
  "analysis": {
    "matchingWithTemples": "寺院とマッチング中...",
    "generatingRecommendations": "推奨結果生成中...",
    "preparingPersonalized": "パーソナライズされた結果準備中...",
    "aiCustomAnalysis": "AIカスタム分析進行中...",
    "findingPerfectTemplestay": "完璧なテンプルステイを探しています...",
    "didYouKnow": "ご存知でしたか？",
    "templestayHistory": "テンプルステイは韓国で1,700年の歴史があります",
    "collectingPreferences": "設定を収集中...",
    "analyzingInputData": "入力データ分析中...",
    "matchingTemples": "寺院マッチング中...",
    "result": {
      "analysisComplete": "分析完了",
      "profileCompleted": "プロフィールが完成しました！",
      "yourCharacteristics": "あなたの特徴",
      "peaceSeekerType": "平和追求型",
      "peaceSeekerDescription": "静かな瞬間と深い内的反省を求めます。瞑想と平和な環境を好みます。",
      "recommendedTemples": "おすすめの寺院",
      "startJourney": "旅を始める",
      "autoRedirect": "メインページに自動移動中...",
      "characteristics": {
        "meditation": "瞑想愛好家",
        "quietTime": "静かな時間を楽しむ",
        "deepConversation": "💭 深い会話を重視"
      },
      "temples": {
        "bulguksa": {
          "name": "仏国寺",
          "location": "慶北慶州",
          "reason": "瞑想と静かな反省に完璧な場所"
        },
        "haeinsa": {
          "name": "海印寺",
          "location": "慶南陜川",
          "reason": "古代仏教経典の本拠地、深い思索に理想的"
        },
        "songgwangsa": {
          "name": "松広寺",
          "location": "全南順天",
          "reason": "平和な雰囲気と瞑想プログラムで有名"
        }
      }
    }
  },
  "language": {
    "selectLanguage": "言語選択",
    "selectLanguageDescription": "テンプルステイアプリで使用する\n言語を選択してください",
    "english": "English",
    "korean": "한국어",
    "japanese": "日本語",
    "chinese": "中文"
  },
  "home": {
    "title": "テンプルステイ",
    "welcome": "心の平和を見つけましょう",
    "viewTemples": "すべての寺院を見る",
    "recommendedTemples": "おすすめの寺院",
    "nearbyTemples": "近くの寺院",
    "popularTemples": "人気の寺院",
    "gyeongbukRecommended": "慶北寺院のおすすめ",
    "myLocation": "現在地",
    "locationBasedRecommendation": "位置ベースの推奨",
    "recommendedTemplesSection": "慶北おすすめ寺院",
    "seeAll": "すべて見る",
    "regions": {
      "all": "すべて",
      "gyeongju": "慶州",
      "andong": "安東",
      "yeongju": "栄州",
      "pohang": "浦項",
      "gumi": "亀尾"
    }
  },
  "temples": {
    "listTitle": "寺院リスト",
    "detailsTitle": "寺院情報",
    "templestayPrograms": "テンプルステイプログラム",
    "reserveNow": "今すぐ予約",
    "price": "価格",
    "duration": "期間",
    "capacity": "収容人数",
    "nearbyAttractions": "近くの観光地"
  },
  "reservation": {
    "selectDate": "日付選択",
    "selectTime": "時間選択",
    "selectPeople": "人数選択",
    "guestInfo": "ゲスト情報",
    "payment": "支払い",
    "confirmation": "予約確認",
    "myReservations": "私の予約",
    "reservationComplete": "予約完了",
    "reserve": "予約",
    "reserveNow": "今すぐ予約",
    "booking": "予約",
    "bookingDetails": "予約詳細",
    "checkIn": "チェックイン",
    "checkOut": "チェックアウト",
    "guests": "ゲスト",
    "adult": "大人",
    "child": "子供",
    "totalPrice": "合計価格",
    "pricePerNight": "1泊料金",
    "serviceFee": "サービス料",
    "taxes": "税金",
    "phoneNumber": "電話番号",
    "email": "メール",
    "specialRequests": "特別なリクエスト",
    "paymentMethod": "支払い方法",
    "creditCard": "クレジットカード",
    "bankTransfer": "銀行振込",
    "confirmReservation": "予約確定",
    "reservationSuccess": "予約成功",
    "reservationFailed": "予約失敗",
    "bookingReference": "予約番号",
    "viewDetails": "詳細を見る",
    "cancel": "キャンセル",
    "modify": "変更",
    "status": {
      "confirmed": "確定",
      "pending": "待機中",
      "cancelled": "キャンセル",
      "completed": "完了"
    }
  },
  "market": {
    "title": "テンプルマーケット",
    "categories": {
      "all": "全て",
      "experience": "体験",
      "goods": "用品",
      "food": "食べ物",
      "books": "書籍"
    },
    "products": {
      "templestayExperience": "テンプルステイ1泊2日体験",
      "templestayDescription": "仏国寺での平和な1泊2日体験",
      "incenseSet": "天然白檀香ギフトセット",
      "incenseDescription": "心を浄化するプレミアム香",
      "cookingClass": "寺院料理クッキングクラス",
      "cookingDescription": "伝統的な韓国寺院料理を学ぶ",
      "meditationCushion": "瞑想クッション",
      "meditationDescription": "瞑想練習用の快適なクッション",
      "teaSet": "伝統茶セット",
      "teaDescription": "平和なティータイムを楽しむ",
      "buddhismBook": "仏教入門",
      "bookDescription": "仏教を理解するための必須ガイド"
    },
    "badges": {
      "popular": "人気",
      "new": "新着",
      "sale": "セール",
      "bestseller": "ベストセラー"
    },
    "price": "価格",
    "originalPrice": "元価格",
    "rating": "評価",
    "reviews": "レビュー",
    "addToCart": "カートに追加",
    "buyNow": "今すぐ購入",
    "viewProduct": "商品を見る",
    "outOfStock": "在庫切れ",
    "inStock": "在庫あり",
    "free": "無料",
    "discount": "割引"
  },
  "map": {
    "search": "場所、住所検索",
    "myLocation": "現在地",
    "nearbyAttractions": "近くの観光地のおすすめ",
    "templeLocation": "寺院の場所",
    "locationPermissionDenied": "位置許可が拒否されました",
    "noSearchResults": "検索結果が見つかりません。慶州、安東、栄州などで検索してみてください",
    "attractionSubtitle": "寺院周辺の美しい名所",
    "searchLocation": "検索位置"
  },
  "profile": {
    "myProfile": "マイプロフィール",
    "editProfile": "プロフィール編集",
    "settings": "設定",
    "language": "言語",
    "notifications": "通知",
    "privacy": "プライバシー",
    "favorites": "お気に入り",
    "notices": "お知らせ",
    "support": "サポートセンター",
    "recentReservation": "最近の予約",
    "visitedPlaces": "訪問した場所",
    "logout": "ログアウト",
    "welcome": "こんにちは！",
    "user": "ユーザー",
    "welcomeSubtitle": "一緒に心の平和を見つけましょう",
    "taxiService": "🚗 テンプルステイタクシーサービス",
    "taxiDescription": "快適な旅行のための便利な交通手段",
    "seeMore": "もっと見る",
    "logoutConfirm": "ログアウトしてもよろしいですか？",
    "logoutError": "ログアウト中にエラーが発生しました",
    "testSuccess": "テスト成功",
    "testFailed": "テスト失敗",
    "testError": "テストエラー",
    "testErrorMessage": "テスト中にエラーが発生しました",
    "developerTools": "開発者ツール",
    "databaseTest": "🔍 データベーステスト",
    "databaseTesting": "データベーステスト中...",
    "colorSystemTest": "カラーシステムテスト",
    "reservationTest": "📝 予約機能テスト",
    "reservationHistory": "予約履歴",
    "visitedTemples": "訪問した寺院"
  },
  "templePreference": {
    "title": "ご希望の体験を選択してください",
    "subtitle": "興味のある活動を選択していただくと\nパーソナライズされたテンプルステイをおすすめします",
    "selectedCount": "個選択済み",
    "hint": "(3個以上選択するとより正確な推奨が可能です)",
    "customAnalysis": "カスタム分析",
    "nextStep": "次へ",
    "activities": {
      "meditation": "瞑想と参禅",
      "meditationDesc": "心の平和を見つける時間",
      "templeFoodExperience": "寺院料理体験",
      "templeFoodDesc": "健康的な寺院料理を学ぶ",
      "bowingPractice": "108拝修行",
      "bowingDesc": "伝統的な懺悔修行法",
      "teaTime": "茶談時間",
      "teaTimeDesc": "僧侶との対話とお茶",
      "dawnService": "朝のお勤め",
      "dawnServiceDesc": "早朝の祈りと瞑想",
      "forestWalk": "森の小道散歩",
      "forestWalkDesc": "自然の中での歩行瞑想",
      "scriptCopying": "経典書写",
      "scriptCopyingDesc": "集中力と心の修養",
      "lotusLanternMaking": "蓮の花灯籠作り",
      "lotusLanternDesc": "伝統工芸体験",
      "communalWork": "合同作業",
      "communalWorkDesc": "共に働く喜び",
      "stoneTowerBuilding": "石塔積み",
      "stoneTowerDesc": "願いを込めた石塔作り",
      "bellTolling": "梵鐘撞き",
      "bellTollingDesc": "神聖な鐘の音体験",
      "sunriseViewing": "日の出鑑賞",
      "sunriseDesc": "山寺での夜明け"
    }
  },
  "locationPreset": {
    "title": "場所を選択してください",
    "subtitle": "あなたに合ったテンプルステイを\nお勧めします",
    "currentLocation": "現在地を使用",
    "currentLocationDesc": "近くの寺院を自動的に見つけます",
    "currentLocationAlert": {
      "title": "現在地使用",
      "message": "位置情報サービスを使用して近くの寺院をお勧めします。",
      "allow": "許可",
      "cancel": "キャンセル"
    },
    "orDivider": "または",
    "directSearch": "直接検索",
    "searchPlaceholder": "都市名を検索してください（例：慶州）",
    "popularLocations": "人気テンプルステイ地域",
    "locationAlert": {
      "title": "場所選択",
      "message": "場所を選択するか検索してください。"
    },
    "popularCities": {
      "gyeongju": "慶州市",
      "gyeongjuDesc": "仏国寺、石窟庵がある歴史の都市",
      "andong": "安東市",
      "andongDesc": "河回村と伝統文化の故郷",
      "yeongju": "栄州市",
      "yeongjuDesc": "小白山と浮石寺の美しい景色",
      "pohang": "浦項市",
      "pohangDesc": "海と共にするテンプルステイ"
    }
  },
  "navigation": {
    "home": "ホーム",
    "temples": "寺院",
    "map": "地図",
    "transportation": "交通",
    "market": "マーケット",
    "myPage": "マイページ"
  }
};