export default {
  "common": {
    "back": "返回",
    "next": "下一步",
    "cancel": "取消",
    "confirm": "确认",
    "search": "搜索",
    "loading": "加载中...",
    "error": "发生错误",
    "retry": "重试",
    "save": "保存",
    "edit": "编辑",
    "delete": "删除",
    "success": "成功",
    "or": "或",
    "skip": "跳过"
  },

  "auth": {
    "login": "登录",
    "signup": "注册",
    "logout": "登出",
    "email": "电子邮件地址",
    "password": "密码",
    "forgotPassword": "忘记密码？",
    "loginWithGoogle": "使用Google登录",
    "loginWithKakao": "使用Kakao登录",
    "loginWithNaver": "使用Naver登录",
    "invalidEmail": "请输入有效的电子邮件地址",
    "enterPassword": "请输入密码",
    "loginFailed": "登录失败",
    "loginError": "登录过程中发生错误",
    "loggingIn": "登录中...",
    "noAccount": "没有账户？注册",
    "fillAllFields": "请填写所有字段",
    "passwordMinLength": "密码至少需要6个字符",
    "agreeToTerms": "请同意条款和条件",
    "signUpComplete": "注册成功完成",
    "googleLogin": "Google登录",
    "googleLoginInstructions": "请在浏览器中完成登录过程",
    "googleLoginError": "Google登录失败",
    "welcomeToApp": "欢迎来到寺院住宿",
    "findPeaceOfMind": "寻找内心的平静",
    "emailLogin": "邮箱登录",
    "continueWithGoogle": "使用Google继续"
  },
  "analysis": {
    "matchingWithTemples": "与寺院匹配中...",
    "generatingRecommendations": "生成推荐结果中...",
    "preparingPersonalized": "准备个性化结果中...",
    "aiCustomAnalysis": "AI定制分析进行中...",
    "findingPerfectTemplestay": "寻找完美的寺院住宿中...",
    "didYouKnow": "您知道吗？",
    "templestayHistory": "寺院住宿在韩国有1,700年的历史",
    "collectingPreferences": "收集您的偏好中...",
    "analyzingInputData": "分析输入数据中...",
    "matchingTemples": "匹配寺院中...",
    "result": {
      "analysisComplete": "分析完成",
      "profileCompleted": "您的个人资料已完成！",
      "yourCharacteristics": "您的特征",
      "peaceSeekerType": "平静追求型",
      "peaceSeekerDescription": "您寻求安静的时刻和深度的内在反思。您喜欢冥想和平静的环境。",
      "recommendedTemples": "推荐寺院",
      "startJourney": "开始您的旅程",
      "autoRedirect": "正在自动跳转到主页面...",
      "characteristics": {
        "meditation": "冥想爱好者",
        "quietTime": "享受安静时光",
        "deepConversation": "💭 重视深度对话"
      },
      "temples": {
        "bulguksa": {
          "name": "佛国寺",
          "location": "庆北庆州",
          "reason": "冥想和安静反思的完美场所"
        },
        "haeinsa": {
          "name": "海印寺",
          "location": "庆南陕川",
          "reason": "古代佛教经文的故乡，深度沉思的理想之地"
        },
        "songgwangsa": {
          "name": "松广寺",
          "location": "全南顺天",
          "reason": "以宁静氛围和冥想项目而闻名"
        }
      }
    }
  },
  "language": {
    "selectLanguage": "选择语言",
    "selectLanguageDescription": "请选择寺院住宿应用\n使用的语言",
    "english": "English",
    "korean": "한국어",
    "japanese": "日本語",
    "chinese": "中文"
  },
  "home": {
    "title": "寺院住宿",
    "welcome": "寻找内心的平静",
    "viewTemples": "查看所有寺院",
    "recommendedTemples": "推荐寺院",
    "nearbyTemples": "附近寺院",
    "popularTemples": "热门寺院",
    "gyeongbukRecommended": "庆北寺院推荐",
    "myLocation": "我的位置",
    "locationBasedRecommendation": "基于位置的推荐",
    "recommendedTemplesSection": "庆北推荐寺院",
    "seeAll": "查看全部",
    "regions": {
      "all": "全部",
      "gyeongju": "庆州",
      "andong": "安东",
      "yeongju": "荣州",
      "pohang": "浦项",
      "gumi": "龟尾"
    }
  },
  "temples": {
    "listTitle": "寺院列表",
    "detailsTitle": "寺院信息",
    "templestayPrograms": "寺院住宿项目",
    "reserveNow": "立即预订",
    "price": "价格",
    "duration": "持续时间",
    "capacity": "容量",
    "nearbyAttractions": "附近景点"
  },
  "reservation": {
    "selectDate": "选择日期",
    "selectTime": "选择时间",
    "selectPeople": "选择人数",
    "guestInfo": "客人信息",
    "payment": "支付",
    "confirmation": "预订确认",
    "myReservations": "我的预订",
    "reservationComplete": "预订完成",
    "reserve": "预订",
    "reserveNow": "立即预订",
    "booking": "预订",
    "bookingDetails": "预订详情",
    "checkIn": "入住",
    "checkOut": "退房",
    "guests": "客人",
    "adult": "成人",
    "child": "儿童",
    "totalPrice": "总价格",
    "pricePerNight": "每晚价格",
    "serviceFee": "服务费",
    "taxes": "税收",
    "phoneNumber": "电话号码",
    "email": "邮箱",
    "specialRequests": "特殊要求",
    "paymentMethod": "支付方式",
    "creditCard": "信用卡",
    "bankTransfer": "银行转账",
    "confirmReservation": "确认预订",
    "reservationSuccess": "预订成功",
    "reservationFailed": "预订失败",
    "bookingReference": "预订号",
    "viewDetails": "查看详情",
    "cancel": "取消",
    "modify": "修改",
    "status": {
      "confirmed": "已确认",
      "pending": "待处理",
      "cancelled": "已取消",
      "completed": "已完成"
    }
  },
  "market": {
    "title": "寺院市场",
    "categories": {
      "all": "全部",
      "experience": "体验",
      "goods": "用品",
      "food": "食物",
      "books": "书籍"
    },
    "products": {
      "templestayExperience": "寺院住宿1晚2天体验",
      "templestayDescription": "在佛国寺的宁静1晚2天体验",
      "incenseSet": "天然白檀香礼品套装",
      "incenseDescription": "净化心灵的高品质香",
      "cookingClass": "寺院料理烹饪课程",
      "cookingDescription": "学习传统韩国寺院料理",
      "meditationCushion": "冥想坐垫",
      "meditationDescription": "冥想练习用的舒适坐垫",
      "teaSet": "传统茶具套装",
      "teaDescription": "享受宁静的茶时光",
      "buddhismBook": "佛教入门",
      "bookDescription": "理解佛教的必备指南"
    },
    "badges": {
      "popular": "热门",
      "new": "新品",
      "sale": "促销",
      "bestseller": "畅销书"
    },
    "price": "价格",
    "originalPrice": "原价",
    "rating": "评分",
    "reviews": "评价",
    "addToCart": "加入购物车",
    "buyNow": "立即购买",
    "viewProduct": "查看产品",
    "outOfStock": "已售罄",
    "inStock": "有库存",
    "free": "免费",
    "discount": "折扣"
  },
  "map": {
    "search": "搜索地点、地址",
    "myLocation": "我的位置",
    "nearbyAttractions": "附近景点推荐",
    "templeLocation": "寺院位置",
    "locationPermissionDenied": "位置权限被拒绝",
    "noSearchResults": "未找到搜索结果。请尝试搜索庆州、安东、荣州等",
    "attractionSubtitle": "寺院周围的美丽景点",
    "searchLocation": "搜索位置"
  },
  "profile": {
    "myProfile": "我的个人资料",
    "editProfile": "编辑个人资料",
    "settings": "设置",
    "language": "语言",
    "notifications": "通知",
    "privacy": "隐私",
    "favorites": "收藏夹",
    "notices": "公告",
    "support": "支持中心",
    "recentReservation": "最近预订",
    "visitedPlaces": "访问过的地方",
    "logout": "登出",
    "welcome": "您好！",
    "user": "用户",
    "welcomeSubtitle": "让我们一起寻找内心的平静",
    "taxiService": "🚗 寺院住宿出租车服务",
    "taxiDescription": "舒适旅行的便利交通",
    "seeMore": "查看更多",
    "logoutConfirm": "您确定要登出吗？",
    "logoutError": "登出过程中发生错误",
    "testSuccess": "测试成功",
    "testFailed": "测试失败",
    "testError": "测试错误",
    "testErrorMessage": "测试过程中发生错误",
    "developerTools": "开发者工具",
    "databaseTest": "🔍 数据库测试",
    "databaseTesting": "数据库测试中...",
    "colorSystemTest": "颜色系统测试",
    "reservationTest": "📝 预订功能测试",
    "reservationHistory": "预订历史",
    "visitedTemples": "访问过的寺院"
  },
  "templePreference": {
    "title": "请选择您喜欢的体验",
    "subtitle": "选择您感兴趣的活动\n我们将为您推荐个性化的寺院住宿",
    "selectedCount": "个已选择",
    "hint": "(选择3个或更多将提供更准确的推荐)",
    "customAnalysis": "定制分析",
    "nextStep": "下一步",
    "activities": {
      "meditation": "冥想和禅修",
      "meditationDesc": "寻找内心平静的时光",
      "templeFoodExperience": "寺院料理体验",
      "templeFoodDesc": "学习健康的寺院料理",
      "bowingPractice": "108拜修行",
      "bowingDesc": "传统忏悔修行法",
      "teaTime": "茶谈时间",
      "teaTimeDesc": "与僧人对话和品茶",
      "dawnService": "早课",
      "dawnServiceDesc": "清晨祈祷和冥想",
      "forestWalk": "森林小径漫步",
      "forestWalkDesc": "在自然中步行冥想",
      "scriptCopying": "经文抄写",
      "scriptCopyingDesc": "专注力和心灵修养",
      "lotusLanternMaking": "莲花灯制作",
      "lotusLanternDesc": "传统工艺体验",
      "communalWork": "集体劳动",
      "communalWorkDesc": "共同工作的快乐",
      "stoneTowerBuilding": "石塔堆砌",
      "stoneTowerDesc": "带着愿望建造石塔",
      "bellTolling": "撞钟",
      "bellTollingDesc": "神圣钟声体验",
      "sunriseViewing": "日出观赏",
      "sunriseDesc": "山寺中的黎明"
    }
  },
  "locationPreset": {
    "title": "请选择您的位置",
    "subtitle": "我们将为您推荐\n适合的寺院住宿",
    "currentLocation": "使用当前位置",
    "currentLocationDesc": "我们将自动为您寻找附近的寺院",
    "currentLocationAlert": {
      "title": "使用当前位置",
      "message": "我们将使用位置服务为您推荐附近的寺院。",
      "allow": "允许",
      "cancel": "取消"
    },
    "orDivider": "或",
    "directSearch": "直接搜索",
    "searchPlaceholder": "搜索城市名称（例如：庆州）",
    "popularLocations": "热门寺院住宿地区",
    "locationAlert": {
      "title": "位置选择",
      "message": "请选择位置或搜索。"
    },
    "popularCities": {
      "gyeongju": "庆州市",
      "gyeongjuDesc": "拥有佛国寺、石窟庵的历史之城",
      "andong": "安东市",
      "andongDesc": "河回村和传统文化之乡",
      "yeongju": "荣州市",
      "yeongjuDesc": "小白山和浮石寺的美丽景色",
      "pohang": "浦项市",
      "pohangDesc": "与大海同在的寺院住宿"
    }
  },
  "navigation": {
    "home": "首页",
    "temples": "寺院",
    "map": "地图",
    "transportation": "交通",
    "market": "市场",
    "myPage": "我的页面"
  },
  "onboarding": {
    "welcomeTitle": "欢迎来到TempleBuk",
    "welcomeSubtitle": "开始您愉快的寺庙住宿体验！",
    "profileImage": "个人资料图片",
    "openGallery": "打开相册",
    "setDefaultImage": "设置默认图片",
    "enterName": "请输入您的姓名",
    "start": "开始",
    "permissionNeeded": "需要权限",
    "photoLibraryPermission": "请授予访问照片库的权限",
    "invalidImage": "选择的图片无效",
    "failedToPickImage": "选择图片失败，请重试"
  }
};